name: gogotrip
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.5.0
  firebase_database: ^10.0.10

  json_serializable: ^6.6.0
  flutter_rating_bar: ^4.0.1
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts:

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  pedantic: ^1.11.1
  test: ^1.22.0


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
#  fonts:
#    - family: Nunito
#      fonts:
#        - asset: fonts/Nunito-VariableFont_wght.ttf
#        - asset: fonts/Nunito-Italic-VariableFont_wght.ttf
#          style: italic

